baseURL = 'https://projects.openrailassociation.org/'
languageCode = 'en-us'
title = 'OpenRail Project Handbook'

[module]
  [[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = '../docs'
    target = 'content/docs'
