name: Website build and deploy

on:
  # Pushes to your main branch, triggering
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, closed]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment. However, do NOT cancel in-progress runs as we want to allow
# especially production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Set environment variables
env:
  source_dir: "./website"
  artifact_name: "website"
  condition_production: ${{ github.ref == 'refs/heads/main' }}
  dir_preview_subdir: proj-pr-${{ github.event.number }}

permissions:
  contents: read # for actions/checkout

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive # Get submodules
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: false

      - name: Setup required build tools with mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Build production site
        run: mise run build
        if: env.condition_production == 'true'

      - name: Build preview site
        env:
          VARS_WEB_DOMAIN_PREVIEW: ${{ vars.WEB_DOMAIN_PREVIEW }}
        run: mise run build-preview -b ${VARS_WEB_DOMAIN_PREVIEW}/${dir_preview_subdir}/
        if: github.event.pull_request

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.source_dir }}/public
          include-hidden-files: true
          retention-days: 1

  deploy:
    name: Deploy website
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write # required unless you explicitly set sticky_comment_enabled: false
      # deployments: write # required if gh_deployment is set
    steps:
      - uses: OpenRailAssociation/web-deployment-action@866b5120138b7deddc2c1e3600bc897a39bd8c91 # v1.3.1
        with:
          artifact_name: ${{ env.artifact_name }}
          condition_production: ${{ env.condition_production }}
          domain_production: https://projects.openrailassociation.org
          domain_preview: ${{ vars.WEB_DOMAIN_PREVIEW }}
          dir_base: ${{ vars.WEB_DIR_BASE }}
          dir_production: projects.openrailassociation.org
          dir_preview_base: ${{ vars.WEB_DIR_PREVIEW_BASE }}
          dir_preview_subdir: ${{ env.dir_preview_subdir }}
          ssh_host: ${{ vars.WEB_SSH_HOST }}
          ssh_user: ${{ vars.WEB_SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          linkchecker_exclude: "https://github.com/orgs/OpenRailAssociation/projects/13,loomio.eu"
